### ISSUE TITLE
when I clicked on login or upload button, I got this error.

### ISSUE THREAD

**Issue by Web2Integrators** [gioboa/qwik-tiktok-microfrontends#1]
Internal assert, this is likely caused by a bug in Qwik: render: notified host element must have a defined $renderQrl$ Object Error: Internal assert, this is likely caused by a bug in Qwik: render: notified host element must 
![Uploading Screenshot 2024-03-17 at 10.02.36 PM.png…]()

**Comment by gioboa** [comment]
Can you try with the latest commit pls?

**Comment by gioboa** [comment]
It's working fine now. 
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Comment by Web2Integrators** [comment]
Hello

How are you?
Nice to know it’s working.

I have some questions on Micro front ends.

I will post those questions tomorrow in Discord channel.


I rally appreciate you have taken Initiative in Qwik micro front end.



I will take latest changes tomorrow morning and then update you.

Thanks

Jay
